CREATE DATABASE YoutubeClone
GO

USE YoutubeClone
GO

CREATE TABLE Usuarios(
	UsuarioID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	UserName NVARCHAR(30) UNIQUE NOT NULL,
	ShowName NVARCHAR(40) NOT NULL,
	Email NVARCHAR(50) UNIQUE NOT NULL,
	BirthDate DATETIME2 NOT NULL,
	Password NVARCHAR(20) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);

CREATE TABLE Canal(
	CanalID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	UsuarioID UNIQUEIDENTIFIER NOT NULL REFERENCES Usuarios(UsuarioID),
	ShowName NVARCHAR(30) NOT NULL,
	UserCanal NVARCHAR(30) UNIQUE NOT NULL,
	Verificacion BIT NOT NULL DEFAULT (0),
	Descripcion NVARCHAR(255) NULL,
	AvatarURL NVARCHAR(255) NULL,
	BannerURL NVARCHAR(255) NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);

CREATE TABLE Notificacion(
	NotificacionID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Titulo NVARCHAR(30) NOT NULL,
	Contenido NVARCHAR(100) NOT NULL,
	MiniaturaURL NVARCHAR(255),
	Interaccion BIT NOT NULL DEFAULT (0),
);

CREATE TABLE VideosAccesibilidad(
	VideosAccesibilidadID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	Nombre NVARCHAR(30) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);

INSERT INTO VideosAccesibilidad(Nombre)
VALUES
('Publico'),
('Privado'),
('No listado');

SELECT * FROM VideosAccesibilidad --prueba

CREATE TABLE ReaccionTipo(
	ReaccionTipoID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	Nombre NVARCHAR(30) NOT NULL,
	ReaccionChange DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);

INSERT INTO ReaccionTipo(Nombre)
VALUES
('Like'),
('Dislike');

CREATE TABLE Video(
	VideoID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	CanalID UNIQUEIDENTIFIER NOT NULL REFERENCES Canal(CanalID),
	--ReaccionTipoID INT NOT NULL REFERENCES ReaccionTipo(ReaccionTipoID),
	Titulo NVARCHAR(100) NOT NULL,
	Descripcion NVARCHAR(255) NULL,
	DuracionSeg INT NOT NULL,
	MiniaturaURL NVARCHAR(255) NOT NULL,
	FechaPublicacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	RestriccionEdad BIT NOT NULL DEFAULT (0),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);

CREATE TABLE HistoricoVideos(
	HistoricoID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	UsuarioID UNIQUEIDENTIFIER NOT NULL REFERENCES Usuarios(UsuarioID),
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	PorcentajeReproducido INT NOT NULL,
	FechaVisualizacion DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);

CREATE TABLE Etiquetas(
	EtiquetaID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	Nombre NVARCHAR(15),
);

CREATE TABLE Comentario(
	ComentarioID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	UsuarioID UNIQUEIDENTIFIER NOT NULL REFERENCES Usuarios(UsuarioID),
	VideoID UNIQUEIDENTIFIER NOT NULL REFERENCES Video(VideoID),
	Contenido NVARCHAR(255) NOT NULL,
	AncladoStatus BIT NOT NULL DEFAULT (0),
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	DeletedAt DATETIME2 NULL,
);

CREATE TABLE TipoCreador(
	TipoCreadorID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	Nombre NVARCHAR(30) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);

INSERT INTO TipoCreador(Nombre)
VALUES
('Usuario'),
('Canal');

SELECT * FROM TipoCreador --prueba

CREATE TABLE ListaReproduccion(
	Lista
);